baseURL = "https://47revisions.com"
languageCode = "en-us"
title = "47Revisions"
theme = "podcast"
publishDir = "docs"
paginate = 5

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  author = "Antonija Pek"
  mp3 = ""
  ogg = ""

[permalinks]
  podcasts = "/:title/"

  [params]
  author = "Antonija Pek"
  description = "A Product designer based in Helsinki talks about the UX design, coding and everything in-between."